### ISSUE TITLE
feat: add MacOS configs

### ISSUE THREAD

**Issue by realeinherjar** [realeinherjar/flakes-darwin#1]
We need to leave `brew`. It is a shitcoin in Ruby.

This is going to be a huge TODO list, but in much need.
Start from scratch:

- [x] backup `main` to a `nix-os` branch
- [x] archive `realeinherjar/MacOS`
- [x] use the `both` template from [`nixos-flakes`](https://zero-to-flakes.com/nixos-flake/templates) : `nix flake init -t github:srid/nixos-flake`
- [x] username: `einherjar`
- [x] hostname: `macbook`
- [x] follow `nixpkgs-unstable`
- [x] add all `brew` packages in https://github.com/realeinherjar/MacOS/blob/b2826c28121e5fc05805463c0b4793d86f3f9579/setup.sh#L17-L79 to packages
  - [x] add [`delta`](https://github.com/dandavison/delta), also update the [`git` configs](https://nix-community.github.io/home-manager/options.html#opt-programs.git.delta.enable) and [getting started from `delta` configs](https://github.com/dandavison/delta?tab=readme-ov-file#get-started)
  - [x] add `nil` and `nixpkgs-fmt`
  - [x] add `alacritty`
    - [x] [`catppuccin` colorscheme](https://github.com/alacritty/alacritty-theme/blob/master/themes/catppuccin.yaml) (check if matches with `catppuccin_mocha`)
    - [x] some options:
       ```yml
       env:
         TERM: xterm-256color
       shell:
         program: zsh
         args:
           - -l
           - -c
           - "source ~/.zshrc; tmux attach 2> /dev/null || tmux"
       window:
         decorations: buttonless
         opacity: 1.0
         window_decorations_theme: dark
         columns: 0
         lines: 0
         startup_mode: Windowed
       font:
         normal:
           family: "NotoSans Nerd Font"
         size: 12.09
       hints:
         enabled:
           - regex:
               "(ipfs:|ipns:magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:|www)\
               [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
             command: open
             post_processing: true
             mouse:
               enabled: true
               mods: Command
             binding:
               key: U
               mods: Command|Shift
       live_config_reload: true
       ```
- [x] add all `cask` packages in https://github.com/realeinherjar/MacOS/blob/b2826c28121e5fc05805463c0b4793d86f3f9579/setup.sh#L85-L106 to mac only
- [x] use `direnv`, instructions [here](https://zero-to-flakes.com/direnv)
- [x] README should follow [`srid/nixos-config`](https://github.com/srid/nixos-config) 
- [x] Add all the hardening in https://github.com/realeinherjar/MacOS/blob/b2826c28121e5fc05805463c0b4793d86f3f9579/setup.sh#L141-L318 using the [`nix-darwin` configuration options](https://daiderd.com/nix-darwin/manual/index.html)
  - [x] Wallpaper
  - [x] Firewall
  - [x] Dark Mode
  - [x] Sharing
  - [x] https://medium.com/@zmre/nix-darwin-quick-tip-activate-your-preferences-f69942a93236 
- [x] Options from [`dustinlyons/nixos-config`](https://github.com/dustinlyons/nixos-config/blob/main/darwin/default.nix)
  - [x] `darwin/default.nix`: `system`, `launchd`, `nix`, and `services`
- [x] Default apps:
  - [x] Video: IINA
  - [x] Browser: Brave
- [x] Dock Configs 
- [x] Karabiner Configs
- [x] Migrate specific configs:
  - [x] `modules/editors/helix.nix`
  - [x] `modules/fonts/default.nix`
  - [x] `modules/shell/tmux.nix`
  - [x] `modules/programs/common/gpg/default.nix` (caveat: remove `pinentryFlavor`)
  - [x] `modules/programs/common/ssh/default.nix`
  - [x] `modules/programs/common/yt-dlp/default.nix` (maybe add this to `cli.nix`)
  - [x] `modules/shell/git.nix`
  - [x] `modules/shell/fish`:
    - [x] update `fish_user_paths` in `modules/shell/fish/fish_variables.nix`
      - add a with `lib.mkIf pkgs.stdenv.isLinux` or `lib.mkIf pkgs.stdenv.isDarwin` to that concatenates either:
        - `SETUVAR fish_user_paths:/home/einherjar/\x2enpm\x2dglobal/bin\x1e/home/einherjar/\x2ecargo/bin`
        - `SETUVAR fish_user_paths:/Users/einherjar/\x2enpm\x2dglobal/bin\x1e/Users/einherjar/einherjar/\x2ecargo/bin`
    - [x] Remove `n.nix`, `owf.nix`, `xdg-get.nix`, and `xdg-set.nix`
    - [x] Remove the `loginShellInit` in `modules/shell/fish/fish.nix`
  - [x] `modules/programs/common/search/default.nix` (maybe add this to `cli.nix`)
    - [x] `fzf`
    - [x] `bat`
    - [x] `zoxide`
    - [x] `yazi`
    - [x] `eza`
    - [x] `broot`
  - [x] `btop` in `modules/programs/common/resource_monitor/default.nix`
- [x] catppuccin everything:
  - [x] `btop`: `modules/theme/catppuccin-dark/common/btop`
  - [x] `fish`: `modules/theme/catppuccin-dark/common/fish/default.nix`
  - [x] `bat`: <https://github.com/catppuccin/bat>
  - [x] `btop`: <https://github.com/catppuccin/btop>
  - [x] `fish`: <https://github.com/catppuccin/fish>
  - [x] `fzf`: <https://github.com/catppuccin/fzf>
  - [x] `tmux`: <https://github.com/catppuccin/tmux>
  - [x] `lazygit`: <https://github.com/catppuccin/lazygit>
  - [x] `alacritty`: <https://github.com/catppuccin/alacritty>
  - [x] `cmus`: <https://github.com/Sekki21956/cmus>
- [x] [`TheFox/cmus-control`](https://github.com/TheFox/cmus-control)

Personal stuff:

- [x] copy `books` and `music`
- [x] backup `Brave`, `Bisq`, `Sparrow`, `Tor Browser` bookmarks, movies, documents
