### ISSUE TITLE
feat(helix): Multiple LSPs

### ISSUE THREAD

**Issue by realeinherjar** [realeinherjar/flakes-darwin#13]
Current version of Helix (23.05) does not support, but this is already implemented in `master`.

Block 🪨 by Helix new release

---

- [ ] verify helix version with `hx -V`
- [ ] `languages.toml`:

  ```toml
  [[language]]
  name = "markdown"
  language-servers = ["marksman", "ltex-ls"]
  formatter = { command = "dprint", args = ["fmt", "--stdin", "md"]}
  auto-format = true
  
  [language-server.ltex-ls]
  command = "ltex-ls"
  [language-server.ltex-ls.config]
  ltex.language = "en-US"
  ltex.disabledRules = { "en-US" = ["PROFANITY"] }
  ltex.dictionary = { "en-US" = ["builtin"] }
  ```

- [ ] `helix.nix`:

  ```nix
  pkgs = [
    ...
    ltex-ls
    dprint
  ]
  ```

- [ ] extend support to $\LaTeX$ and bibfiles: https://valentjn.github.io/ltex/
